#!/bin/bash
# Purpose: This script will copy currently tracked config files
# to the current directory

# Config Files in $HOME/.config/
cp -rf ~/.config/i3/ $PWD/.config
cp -rf ~/.config/polybar/ $PWD/.config
cp -rf ~/.config/compton.conf $PWD/.config

# Config Files in $HOME
cp -rf ~/.vimrc $PWD

echo "Finished"
