#!/bin/sh
#
# pandocWatch
#
# Watches the markdown file (*.md) specified, and compiles it using
# Pandoc on each save.
#

INPUT="$@"
OUTPUT=~/default.pdf
FLAGS='--listings -H /home/cooper/.pandoc/header.tex'

if [ -z "$INPUT" ]; then
	echo "Error: Missing filename argument"
	echo "You must specify a markdown file for pandocWatch to use."
	exit 1
fi

# Verify that file exists
if [ ! -f "$@" ]; then
    echo "Error: Specified file not found"
    exit 1
fi


if [ "${INPUT##*.}" != "md" ]; then
	echo "Error: pandocWatch can only be used on Markdown (.md) files."
	exit 1
fi

# Trigger an initial run
echo "`date +"%H:%M:%S"` - Processing $INPUT... "
pandoc $FLAGS -o $OUTPUT "$@"

# Open window for live preview of PDF
zathura $OUTPUT &

# Continuously compile on save
echo "`date +"%H:%M:%S"` - Watching $INPUT... "

while true; do
	inotifywait -q -e modify "$@"
	echo "`date +"%H:%M:%S"` - Processing $INPUT... "
	pandoc $FLAGS -o $OUTPUT "$@"

	if [ $? -eq 0 ]; then
		echo "Complilation Successful"
	else
		echo "Compilation Error"
	fi
done

