#!/bin/sh
#
# Watches the markdown file (*.md) specified, and compiles it using
# Pandoc on each save.

################################################################################
# Default Flags to be used

INPUT="$@"
OUTPUT=~/default.pdf

PANDOC_HEADER="/home/cooper/.pandoc/header.tex" 	# Extension header file
PANDOC_FLAGS="--listings -H $PANDOC_HEADER"

################################################################################

# Verify the correct file has been given
verifyFile () {
	if [ -z "$1" ]; then
		print_usage
		echo "Error: Missing filename argument"
		echo "You must specify a markdown file for pandocWatch to use."
		exit 1
	fi

	# Verify that file exists
	if [ ! -f "$1" ]; then
		echo "Error: Specified file not found"
		exit 1
	fi

	if [ "${1##*.}" != "md" ]; then
		echo "Error: pandocWatch can only be used on Markdown (.md) files."
		exit 1
	fi
}

# Process and output the file
render () {
	echo "`date +"%H:%M:%S"` - Processing $INPUT... "
	pandoc $PANDOC_FLAGS -o $OUTPUT "$INPUT"

	if [ $? -eq 0 ]; then
		echo "Complilation Successful"
	else
		echo "Compilation Error"
	fi
}


verifyFile "$INPUT"

render
# Open window for live preview of PDF
zathura $OUTPUT &

# Continuously compile on save
echo "`date +"%H:%M:%S"` - Watching $INPUT... "

while true; do
	inotifywait -q -e modify "$@"
	render
done

